### ISSUE TITLE
question of your blog named "Tutorial for running OrthoMCL"

### ISSUE THREAD

**Issue by U201412486** [darencard/darencard.github.io#1]
Hi,
  When I read your blog named "Tutorial for running OrthoMCL" at http://darencard.net/blog/2018-01-12-orthomcl-tutorial/, I can not understand the meanning of your sentence below.
`Let’s say we have our protein FASTA files (i.e., _protein.faa) and our annotation data (stored with a _protein_table.txt suffix) stored in a directory called raw in our working directory. `
  Where are your annotation data such as `GCF_000090745.1_AnoCar2.0_protein_table.txt` from? Is it from ncbi ? I can not find the  annotation data of protein.
 I would appreciate it if you would give me a reply.
 Thanks,
 sunxh,

**Comment by darencard** [comment]
Apologies for not providing more detail on that file. I have modified the page so it has instructions for where to download the protein table from NCBI for your genome of interest. Hopefully, that is now clear but please let me know if it is not.

**Comment by U201412486** [comment]
Thank you very much.Your blog helps me a lot.

**Comment by U201412486** [comment]
Hi,
   Merry Christmas!
   In your blog named "Tutorial for running OrthoMCL" at http://darencard.net/blog/2018-01-12-orthomcl-tutorial/, you say `Proteins that are not clustered into othologous groups (i.e., present in at least 2 species) are exluced from the resulting groups.txt output file.` In fact,the resulting groups.txt output file will include groups from just 1 species.In the userguide at https://orthomcl.org/common/downloads/software/v2.0/UserGuide.txt, it say `The groups.txt file contains the groups created by clustering the pairs with the MCL program.` I think it means that The groups.txt include coorthologs,inparalogs and orthologs.Do you think so ?
  best~
  sun,
