### ISSUE TITLE
Repeat Annotation Blog

### ISSUE THREAD

**Issue by ovidp** [darencard/darencard.github.io#2]
Hi Daren
Thanks for the great blogs you are making available.
I have spotted two errors in your https://darencard.net/blog/2022-07-09-genome-repeat-annotation/

1)  -a should point to the known database in the following command (your original is given here):
repclassifier -t 3 -d Tetrapoda -u reference-genome-families.prefix.fa.unknown \
-k reference-genome-families.prefix.fa.known -a reference-genome-families.prefix.fa.unknown \
-o round-1_RepbaseTetrapoda-Self

2) This command fails, with "datamash: invalid input: field 4 requested, line 1 has only 3 fields":
cat 05_full_out/reference-genome.full_mask.out | tail -n +4 | awk -v OFS="\t" '{ print $6, $7, $11 }' | 
awk -F '[\t/]' -v OFS="\t" '{ if (NF == 3) print $3, "NA", $2 - $1 +1; else print $3, $4, $2 - $1 +1 }' | 
datamash -sg 1,2,3 sum 4 | grep -v "\?" | 
awk -v OFS="\t" -v genomeLen="${allLen}" '{ print $0, $4 / genomeLen }' > 05_full_out/reference-genome.full_mask.tabulate

Best, Ovidiu

**Comment by darencard** [comment]
Thanks for catching these issues, Ovidiu!

1. You are correct. I have updated the tutorial.
2. Yes, this results in an error. the datamash command should instead be `datamash -sg 1,2 sum 3`. I have updated the tutorial.
